# This file should contain all the record creation needed to seed the database with its default values.
#起初用户
User.create(:name=>"admin", :password => "123456",:superpasswd => "jikeel123456")
Customer.create(:email=>"test@360sem.cn",:name => "360SEM", :password => "123456")

##商家分类
food = Category.create(:name => "豆豆美食", :key => "food")
food.children.create(:name => "川菜")
food.children.create(:name => "湘菜")
food.children.create(:name => "本帮菜")
entertainment = Category.create(:name => "豆豆娱乐", :key => "entertainment")
entertainment.children.create(:name => "KTV")
entertainment.children.create(:name => "麻将室")
entertainment.children.create(:name => "保龄球")
hostel = Category.create(:name => "豆豆酒店", :key => "hostel")
hostel.children.create(:name => "快捷酒店")
hostel.children.create(:name => "星级酒店")
hostel.children.create(:name => "驴友便捷")
health = Category.create(:name => "豆豆养生", :key => "health")
health.children.create(:name => "足浴养生")
health.children.create(:name => "按摩保健")
##Collection group
biz_area = Group.create(:name => "热门商圈", :key => "biz_area")
Collection.create(:name => "徐家汇", :group => biz_area, :key => "xjh")
Collection.create(:name => "南京东路", :group => biz_area, :key => "njdl")
Collection.create(:name => "外滩", :group => biz_area, :key => "wt")
university_around = Group.create(:name => "大学周边", :key => "university_around")
Collection.create(:name => "复旦大学", :group => university_around, :key => "fddx")
Collection.create(:name => "同济大学", :group => university_around, :key => "tjdx")
Collection.create(:name => "华东师范大学", :group => university_around, :key => "hdsfdx")
industry360 = Group.create(:name => "热门分类（360行）", :key => "360industry")
Collection.create(:name => "养生会所", :group => industry360, :key => "yshs")
Collection.create(:name => "快捷酒店", :group => industry360, :key => "kjjd")
Collection.create(:name => "欢唱K歌", :group => industry360, :key => "hckg")
keywords = Group.create(:name => "关键字", :key => "keywords")
Collection.create(:name => "情侣密约", :group => keywords, :key => "qlmy")
Collection.create(:name => "烛光晚餐", :group => keywords, :key => "zgwc")
#上海区县
sh_counties = Enum.create(:name => "shanghai_counties")
pdxq = sh_counties.options.create(:name => "浦东新区", :key => "pdxq")
sh_counties.options.create(:name => "黄浦区", :key => "hpq")
sh_counties.options.create(:name => "杨浦区", :key => "ypq")
sh_counties.options.create(:name => "闸北区", :key => "zbq")
#商家
Business.create(:name=>"开成公司", :password => "123456", :category => food, :county => pdxq, :phone => "38613568", :active => true)

gender = Enum.create(:name => "gender")
gender.options.create(:name => "男", :key => "man")
gender.options.create(:name => "女", :key => "woman")